### ISSUE TITLE
Where does the Team Link go?

### ISSUE THREAD

**Issue by StevenDufresne** [Automattic/meeting-calendar#27]
Currently, when you click on the name of a team, it applies the `#{team}` to the url and filters the results. 

Do we want to keep that functionality when we click on the team name now?

**What the list looks like now:**
![Screenshot](https://d.pr/i/qoMX3e.png)

**Comment by tellyworth** [comment]
I think it's a useful feature. It could be a bit surprising, in that you might click on that link expecting it to take you to the team page (or p2 or slack or whatever). That could probably be resolved by placing nearby some other well-labelled links to the likely destinations - the `link` and the Slack channel being the main things I can think of.

**Comment by StevenDufresne** [comment]
What about adding a tooltip?

**Comment by StevenDufresne** [comment]
![Tooltip](https://d.pr/i/nxZI1w.png)
