### ISSUE TITLE
Should we let teams control their team's color?

### ISSUE THREAD

**Issue by StevenDufresne** [Automattic/meeting-calendar#32]
I am adding some colors to each teams. Do we want to add that as meta data?

![Screenshot](https://d.pr/i/JU77Og.png)

**Comment by dd32** [comment]
Should colours be based on Team, or Meeting? Currently Teams are metadata of an event, so we don't really have a central store of Teams anyway

The Core Team for example has a lot of different meetings, Core Dev, CSS, JS, Privacy, etc.

**Comment by StevenDufresne** [comment]
Interesting, I wonder if we would run into too many similar colors, making the colors a bit useless. if we did it meeting based.

**Comment by dd32** [comment]
On second thought, yeah per-meeting wouldn't be ideal.

Perhaps we can just hard-code the profile team colours instead - although they're not all the best for contrast with text
eg https://make.wordpress.org/meta/handbook/documentation/profile-badges/

**Comment by StevenDufresne** [comment]
Nice. I'll go with that for now.

**Comment by StevenDufresne** [comment]
@dd32 @tellyworth @ryelle 

Thoughts on associating colors for the list view? Below, surrounded the team name with the color link by @dd32 above.

He also makes a good point about the contrast, especially since have have about ~4 teams that use yellow.

![List View](https://d.pr/i/UtbmJ7.png)


![Calendar](https://d.pr/i/UduYyx.png)

**Comment by tellyworth** [comment]
Yeah that looks great. Are they hard-coded by team name?

**Comment by StevenDufresne** [comment]
Yeah, css styles for each team.

**Comment by tellyworth** [comment]
Yeah that makes sense. We can do that in the Meta-specific stylesheet for the finished release.
