### ISSUE TITLE
Single meeting repeats in the API for `max` times

### ISSUE THREAD

**Issue by ryelle** [Automattic/meeting-calendar#34]
If you add a meeting with no repetition, that starts and ends on the same day, it's expanded out `max` times in the API:

<img width="816" alt="Screen Shot 2020-02-28 at 1 41 11 PM" src="https://user-images.githubusercontent.com/541093/75589575-fd6d8f80-5a2f-11ea-87c2-7e4bc8946036.png">

Note: It's fixed if I select a recurrence, but that's unexpected. Maybe we should add note that it's required?

**Comment by ryelle** [comment]
Well, I edited ^ and said it was fixed if I added an end date, but it's not, actually — now the end date is not respected.

**Comment by tellyworth** [comment]
Yeah there's something weird happening here. We're not really doing any input validation (see #36). I don't think the old calendar was ever really used for single events, but there's no reason it shouldn't be.

Interestingly, the bug doesn't seem to occur if the date is on the next month's page of meetings; only if it's on the first.
