### ISSUE TITLE
The Calendar Navigation Buttons are useless ATM since no data is populated.

### ISSUE THREAD

**Issue by StevenDufresne** [Automattic/meeting-calendar#40]
We have three buttons `today`, `next`, `previous`. They work fine, but we don't populate data into the future of the past. What to we do with them?

**Options**:
1. Keep them, populate data
2. Remove them.
3. Keep next button since we do have that data populated.

**Comment by tellyworth** [comment]
I think the MVP approach might be to keep the buttons, but only allow navigating to this month and next month.

It's a bit of an accident of old code that the API returns more than a month's worth of data currently. I might make that more explicit, so we could intentionally fetch two months worth of data to populate two calendar pages. Sound reasonable?
