### ISSUE TITLE
Which date should we use for getting the data.

### ISSUE THREAD

**Issue by StevenDufresne** [Automattic/meeting-calendar#50]
In `plugin.php` we currently set the date to 1 week behind the current date. 
`date( 'Y-m-d', strtotime( '-1 week' ) );`

**What would be the best approach?**
 I was thinking that we could request data back to the start of the month, but would that mean we don't have all the data for the next month?

**Comment by ryelle** [comment]
I switched to using `date( 'Y-m-01' )` for some local testing at the end of Feb, could we do that & return 8 weeks of data?

Also, [the `per_page` set here](https://github.com/Automattic/meeting-calendar/blob/71fda37038ed84e35961c9900de6a15fe83067d4/plugin.php#L23) isn't used by this endpoint, so we could remove that (or use it to specify a number of weeks?)

**Comment by StevenDufresne** [comment]
@tellyworth What are your thoughts?

**Comment by tellyworth** [comment]
Yeah I agree with @ryelle, two months starting at the beginning of the current month seems fair. That should be easy enough to support in the back end, I'll look into it.

I don't think we're doing anything at present to show that past events are finished, should we grey them out or something?

**Comment by StevenDufresne** [comment]
> Yeah I agree with @ryelle, two months starting at the beginning of the current month seems fair. That should be easy enough to support in the back end, I'll look into it.
> 
> I don't think we're doing anything at present to show that past events are finished, should we grey them out or something?

Feel free to update `plugin.php` to match. There aren't any other front end changes that are needed.

**Comment by tellyworth** [comment]
See #59. I'll need to do something about the unit tests that now fail but it seems to work.

**Comment by StevenDufresne** [comment]
Completing in https://github.com/Automattic/meeting-calendar/pull/59
