### ISSUE TITLE
Add timezones where dates are displayed.

### ISSUE THREAD

**Issue by StevenDufresne** [Automattic/meeting-calendar#77]
We should add the local timezone and its offset where we display dates:

Ie: `...9:00 pm KST(UTC+9)`

**Locations:**
- Modal window
- List item
- Shortcodes

I don't think we need it on the button in the calendar view.

**Notes:**
- Don't forget about things like `CST` and `CDT`

**Comment by StevenDufresne** [comment]
It doesn't appear like we can consistently support adding the local timezone `KST`.

It was [removed from `moment.js`](https://github.com/moment/moment/issues/162) and we need the timezone (`America/Los_Angeles`) to run abbreviations with [moment timezone](https://momentjs.com/timezone/)

**Comment by StevenDufresne** [comment]
@tellyworth @ryelle @dd32 

Does this work?

![calendar](https://d.pr/i/ZPYCE7.png)
![list](https://d.pr/i/5Vot5v.png)

**Comment by dd32** [comment]
@StevenDufresne That looks good to me within the limitations of JS timezone support.
